# Generated by Django 4.0.1 on 2022-01-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
                ('treeimg', models.FileField(upload_to='treeimg/jpg/')),
                ('comment', models.CharField(max_length=40)),
            ],
        ),
    ]
