# Generated by Django 4.0.1 on 2022-01-30 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree_project',
            name='comment',
        ),
    ]
