# Generated by Django 4.0.1 on 2022-01-30 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0002_remove_tree_project_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree_project',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
