# Generated by Django 4.0.1 on 2022-01-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0003_tree_project_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree_project',
            name='treeimg',
        ),
        migrations.AddField(
            model_name='tree_project',
            name='treeimage',
            field=models.ImageField(default='default.jpg', upload_to='treeimages/'),
        ),
    ]
